[package]
authors = ["Without Boats <woboats@gmail.com>"]
description = "Experimental error handling abstraction."
license = "MIT OR Apache-2.0"
name = "failure"
version = "0.0.1"

[dependencies.backtrace]
version = "0.3.3"
